#!/usr/bin/env python3
"""
gen-estate.py — emit ESTATE.md from the repo, and gate it against drift.

WHY THIS IS GENERATED AND NEVER HAND-EDITED
-------------------------------------------
Two briefs named ESTATE.md as the home for repo/site truth (routes, sitemap,
llms.txt, CI gates), and one said it "regenerates on merge". It did not exist,
and nothing regenerated it -- found 2026-09-16 while executing the /p/{slug}
ruling, which had no canonical home to point at (registry v3.66).

A hand-written ESTATE.md would be the fifth copy of facts the repo already
holds, and this month has been one long demonstration of what a second copy
costs: the canon copy in a Project prompt (v3.61), "the skill wins on conflict"
(v3.62), the partner-registry person-names call (v3.63). A copy cannot be kept
honest; it can only be derived or removed.

So this file is DERIVED. The repo is the source. CI regenerates and compares, so
ESTATE.md cannot say something the repo does not.

Usage:
  python3 scripts/gen-estate.py           # --check: fail if ESTATE.md is stale
  python3 scripts/gen-estate.py --write   # regenerate it
"""
import os, re, sys, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "ESTATE.md")
SKIP = ("/.git", "/node_modules", "/scratchpad", "/.lighthouseci")


def pages():
    out = []
    for dp, _, fs in os.walk(ROOT):
        if any(x in dp for x in SKIP):
            continue
        for f in fs:
            if not f.endswith(".html"):
                continue
            rel = os.path.relpath(os.path.join(dp, f), ROOT)
            if rel == "404.html":
                url = "/404"
            elif rel.endswith("/index.html"):
                url = "/" + rel[: -len("/index.html")]
            elif rel == "index.html":
                url = "/"
            else:
                url = "/" + rel[: -len(".html")]
            out.append((url, rel))
    return sorted(out)


def redirects():
    p = os.path.join(ROOT, "_redirects")
    rows = []
    if os.path.exists(p):
        for line in open(p, encoding="utf-8"):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) >= 2:
                rows.append((parts[0], parts[1], parts[2] if len(parts) > 2 else "301"))
    return rows


def gates():
    p = os.path.join(ROOT, "scripts", "validate-site.py")
    if not os.path.exists(p):
        return []
    src = open(p, encoding="utf-8").read()
    found = re.findall(r"^\s*#\s*(\d+[a-z]?(?:-\d)?)\.\s+(.+)$", src, re.M)
    seen, rows = set(), []
    for num, desc in found:
        if num in seen:
            continue
        seen.add(num)
        rows.append((num, desc.strip().rstrip(".")))
    return rows


def counted(path, pattern):
    p = os.path.join(ROOT, path)
    if not os.path.exists(p):
        return 0
    return len(re.findall(pattern, open(p, encoding="utf-8").read()))


def robots_of(rel):
    src = open(os.path.join(ROOT, rel), encoding="utf-8").read()
    m = re.search(r'<meta\s+name="robots"\s+content="([^"]*)"', src)
    return m.group(1) if m else ""


def build():
    ps = pages()
    noindexed = [(u, r) for u, r in ps if "noindex" in robots_of(r)]
    L = []
    A = L.append
    A("# ESTATE.md — what the repo actually is")
    A("")
    A("> **Status:** STATE")
    A("> **Date:** 2026-09-16")
    A("> **Supersedes:** nothing — this file did not exist until 2026-09-16 (registry v3.66)")
    A("> **On conflict:** the repo wins. This file is GENERATED from it by "
      "`scripts/gen-estate.py` and is never hand-edited; CI fails if the two disagree.")
    A("")
    A("**Do not edit this file.** Change the repo and run `python3 scripts/gen-estate.py --write`.")
    A("A hand-edit is a second source of truth, and it will be overwritten.")
    A("")
    A("---")
    A("")
    A("## Routes")
    A("")
    A(f"**{len(ps)} pages.**")
    A("")
    A("| URL | File | robots |")
    A("|---|---|---|")
    for u, r in ps:
        A(f"| `{u}` | `{r}` | {robots_of(r) or '—'} |")
    A("")
    A(f"**{len(noindexed)} noindex:** " + ", ".join(f"`{u}`" for u, _ in noindexed))
    A("")
    A("### Redirects and rewrites (`_redirects`, first match wins)")
    A("")
    A("| From | To | Status |")
    A("|---|---|---|")
    for f, t, s in redirects():
        A(f"| `{f}` | `{t}` | {s} |")
    A("")
    A("## Listings")
    A("")
    A(f"- `sitemap.xml` — **{counted('sitemap.xml', r'<loc>')}** URLs")
    llms_n = counted("llms.txt", r"^\s*-\s*\[")
    A(f"- `llms.txt` — **{llms_n}** entries "
      "(gated against sitemap.xml by `scripts/gen-llms.py`)")
    A("")
    A("## CI gates (`scripts/validate-site.py`)")
    A("")
    A(f"**{len(gates())} numbered gates.** Each fails the build.")
    A("")
    A("| # | Gate |")
    A("|---|---|")
    for n, d in gates():
        A(f"| {n} | {d} |")
    A("")
    A("---")
    A("")
    A("*Generated by `scripts/gen-estate.py`. Regenerate after any change to routes, "
      "`_redirects`, `sitemap.xml`, `llms.txt` or the validator.*")
    return "\n".join(L) + "\n"


def main():
    want = build()
    if "--write" in sys.argv:
        open(OUT, "w", encoding="utf-8").write(want)
        print(f"✓ ESTATE.md written ({len(want.splitlines())} lines)")
        return 0
    if not os.path.exists(OUT):
        print("✗ ESTATE.md missing — run: python3 scripts/gen-estate.py --write")
        return 1
    have = open(OUT, encoding="utf-8").read()
    if have != want:
        print("✗ ESTATE.md is STALE — the repo changed and the file did not.\n"
              "   Run: python3 scripts/gen-estate.py --write\n"
              "   (It is generated, never hand-edited — a hand-edit is a second "
              "source of truth.)")
        return 1
    print("✓ ESTATE.md matches the repo")
    return 0


if __name__ == "__main__":
    sys.exit(main())
